---
blank_issues_enabled: true
contact_links:
  - name: Official Support
    url: https://support.fwerkor.com
    about: If you need business support, consider reaching out to get help. CapOS is a complex software project with many pitfalls; there is a good chance someone can help you solve your issue in no time.
  - name: FWERKOR Blog
    url: https://blog.fwerkor.com/archives/category/fwerkor_projects/capos
    about: The CapOS documentation contains a lot of valuable information.
